import type { Restaurant } from './types';

// ── 관리자DB(구글 시트) mock — Phase 1용 큐레이션 맛집 ──────
// Phase 0에서 실제 시트로 교체. 좌표는 양재/강남/서초 인근 실측 근사값.

export const MOCK_RESTAURANTS: Restaurant[] = [
  {
    name: '양재역 한우국밥',
    categoryMain: '한식',
    categorySub: '국밥·탕',
    signatureMenu: '한우 소고기국밥',
    visited: true,
    rating: 9,
    priceTier: '가성비',
    priceNote: '인당 1.1만',
    address: '서울 서초구 남부순환로 2795',
    lat: 37.4845,
    lng: 127.0348,
    comment: '점심 웨이팅 있지만 회전 빠름. 혼밥 최적',
    active: true,
    weight: 2,
    mealType: '둘다',
    groupSeating: false,
    phone: '02-576-1234',
    soloFriendly: true,
  },
  {
    name: '매봉 손칼국수',
    categoryMain: '한식',
    categorySub: '면류(칼국수·냉면)',
    signatureMenu: '바지락 손칼국수+겉절이',
    visited: true,
    rating: 7,
    priceTier: '가성비',
    priceNote: '인당 0.9만',
    address: '서울 강남구 남부순환로 2734',
    lat: 37.4867,
    lng: 127.0301,
    comment: '면 직접 뽑음. 든든한 혼밥',
    active: true,
    weight: 1,
    mealType: '점심',
    groupSeating: false,
    soloFriendly: true,
  },
  {
    name: '강남 스시하나',
    categoryMain: '일식',
    categorySub: '초밥·회',
    signatureMenu: '점심 특선 스시 12피스',
    visited: true,
    rating: 8,
    priceTier: '보통',
    priceNote: '인당 2.8만',
    address: '서울 강남구 강남대로 320',
    lat: 37.4951,
    lng: 127.028,
    comment: '가성비 좋은 런치 오마카세',
    active: true,
    weight: 1,
    mealType: '둘다',
    groupSeating: false,
    phone: '02-501-8888',
    soloFriendly: false,
  },
  {
    name: '서초 화로갈비',
    categoryMain: '한식',
    categorySub: '고기구이',
    signatureMenu: '한우 모둠구이 코스',
    visited: true,
    rating: 9,
    priceTier: '회식',
    priceNote: '인당 5.5만',
    address: '서울 서초구 서초대로 302',
    lat: 37.4933,
    lng: 127.0246,
    comment: '단체룸 완비. 회식 단골',
    active: true,
    weight: 2,
    mealType: '저녁',
    groupSeating: true,
    groupCapacity: 24,
    phone: '02-3473-2000',
    soloFriendly: false,
  },
  {
    name: '양재 이자카야 토리',
    categoryMain: '일식',
    categorySub: '초밥·회',
    signatureMenu: '사시미+꼬치 코스',
    priceTier: '회식',
    priceNote: '인당 5.0만',
    address: '서울 서초구 강남대로 27길 8',
    lat: 37.4838,
    lng: 127.0335,
    comment: '단체석 있음. 번개모임에도 좋음',
    active: true,
    weight: 1,
    mealType: '저녁',
    groupSeating: true,
    groupCapacity: 16,
    phone: '02-577-9090',
    soloFriendly: false,
  },
  {
    name: '교대 마라공방',
    categoryMain: '중식',
    categorySub: '마라·훠궈',
    signatureMenu: '마라샹궈+꿔바로우',
    visited: true,
    rating: 8,
    priceTier: '보통',
    priceNote: '인당 2.2만',
    address: '서울 서초구 서초중앙로 118',
    lat: 37.4935,
    lng: 127.0143,
    comment: '얼얼한 정통 마라. 2인 이상 추천',
    active: true,
    weight: 1,
    mealType: '둘다',
    groupSeating: true,
    groupCapacity: 12,
    soloFriendly: false,
  },
  {
    name: '방배 파스타공방',
    categoryMain: '양식',
    categorySub: '파스타·피자',
    signatureMenu: '트러플 크림 파스타',
    priceTier: '보통',
    priceNote: '인당 2.4만',
    address: '서울 서초구 방배로 42길 15',
    lat: 37.4812,
    lng: 126.9975,
    comment: '데이트·점심약속 분위기',
    active: true,
    weight: 1,
    mealType: '둘다',
    groupSeating: false,
    soloFriendly: false,
  },
  {
    name: '양재 김밥천사',
    categoryMain: '분식',
    categorySub: '떡볶이·김밥',
    signatureMenu: '즉석 매운떡볶이+참치김밥',
    visited: true,
    rating: 6,
    priceTier: '가성비',
    priceNote: '인당 0.7만',
    address: '서울 서초구 강남대로 213',
    lat: 37.4841,
    lng: 127.0338,
    comment: '빠른 혼밥. 포장 강추',
    active: true,
    weight: 1,
    mealType: '점심',
    groupSeating: false,
    soloFriendly: true,
  },
  {
    name: '강남 라멘야',
    categoryMain: '일식',
    categorySub: '라멘·우동',
    signatureMenu: '돈코츠 차슈라멘',
    visited: true,
    rating: 8,
    priceTier: '가성비',
    priceNote: '인당 1.2만',
    address: '서울 강남구 테헤란로 8길 21',
    lat: 37.4978,
    lng: 127.0276,
    comment: '진한 국물. 바 좌석 많아 혼밥 편함',
    active: true,
    weight: 1,
    mealType: '둘다',
    groupSeating: false,
    soloFriendly: true,
  },
  {
    name: '서초 쌀국수 사이공',
    categoryMain: '아시안',
    categorySub: '쌀국수·베트남',
    signatureMenu: '양지 쌀국수+분짜',
    visited: true,
    rating: 7,
    priceTier: '가성비',
    priceNote: '인당 1.1만',
    address: '서울 서초구 반포대로 30길 12',
    lat: 37.4889,
    lng: 127.0121,
    comment: '깔끔한 국물. 혼밥·점심약속 무난',
    active: true,
    weight: 1,
    mealType: '둘다',
    groupSeating: false,
    soloFriendly: true,
  },
  {
    name: '대치 정성백반',
    categoryMain: '한식',
    categorySub: '찌개·백반',
    signatureMenu: '제육+된장찌개 백반',
    priceTier: '가성비',
    priceNote: '인당 1.0만',
    address: '서울 강남구 도곡로 405',
    lat: 37.4941,
    lng: 127.0621,
    comment: '집밥 느낌. 점심 전용',
    active: true,
    weight: 1,
    mealType: '점심',
    groupSeating: false,
    soloFriendly: true,
  },
  {
    name: '논현 스테이크하우스',
    categoryMain: '양식',
    categorySub: '스테이크·비스트로',
    signatureMenu: '드라이에이징 채끝 스테이크',
    visited: true,
    rating: 9,
    priceTier: '플렉스',
    priceNote: '인당 4.5만',
    address: '서울 강남구 학동로 25길 40',
    lat: 37.5109,
    lng: 127.0335,
    comment: '기념일·플렉스 점심',
    active: true,
    weight: 1,
    mealType: '둘다',
    groupSeating: true,
    groupCapacity: 20,
    phone: '02-541-7700',
    soloFriendly: false,
  },
  {
    name: '동작 중앙시장 순대국',
    categoryMain: '한식',
    categorySub: '국밥·탕',
    signatureMenu: '얼큰 순대국밥',
    priceTier: '가성비',
    priceNote: '인당 0.9만',
    address: '서울 동작구 동작대로 105',
    lat: 37.4776,
    lng: 126.9812,
    comment: '택시 모드에서만 후보. 24시간',
    active: true,
    weight: 1,
    mealType: '둘다',
    groupSeating: false,
    soloFriendly: true,
  },
  {
    name: '잠실 대성갈비 연회장',
    categoryMain: '한식',
    categorySub: '고기구이',
    signatureMenu: '갈비 연회 코스',
    visited: true,
    rating: 8,
    priceTier: '회식',
    priceNote: '인당 6.0만',
    address: '서울 송파구 올림픽로 240',
    lat: 37.5133,
    lng: 127.1028,
    comment: '대형 단체룸. 40명까지. 택시 모드',
    active: true,
    weight: 2,
    mealType: '저녁',
    groupSeating: true,
    groupCapacity: 40,
    phone: '02-421-5000',
    soloFriendly: false,
  },
  {
    // 오버라이드 시연: 사무실과 직선거리는 가깝지만(~350m) 가파른 언덕 위라
    // 도보 접근이 힘든 곳 → access_mode=택시. 직선거리 무시하고 택시 모드에서만 노출.
    name: '언덕 위 감자탕',
    categoryMain: '한식',
    categorySub: '국밥·탕',
    signatureMenu: '뼈해장국',
    priceTier: '가성비',
    priceNote: '인당 1.0만',
    address: '서울 강남구 도곡로 언덕길',
    lat: 37.4915,
    lng: 127.0556,
    comment: '가깝지만 오르막 심함 — 도보 비추, 택시/차량 권장',
    active: true,
    weight: 1,
    mealType: '둘다',
    groupSeating: false,
    accessMode: 'taxi',
    soloFriendly: true,
  },
];

// ── 카카오 로컬 검색 결과 mock (일반 후보) ──────────────────
// 실제 카카오 API 응답 형태를 흉내. 관리자DB에 없는 일반 음식점.

export interface KakaoPlace {
  id: string;
  place_name: string;
  category_name: string;
  address_name: string;
  road_address_name: string;
  x: string; // lng
  y: string; // lat
  phone: string;
  place_url: string;
}

export const MOCK_KAKAO_PLACES: KakaoPlace[] = [
  place('k1', '역전우동0410 양재점', '음식점 > 일식 > 우동', '서울 서초구 양재동', 127.0355, 37.4839, '02-571-0410'),
  place('k2', '홍콩반점0410 강남', '음식점 > 중식 > 중국집', '서울 강남구 역삼동', 127.0301, 37.4988, '02-538-0410'),
  place('k3', '본죽 서초점', '음식점 > 한식 > 죽', '서울 서초구 서초동', 127.0208, 37.4922, '02-3474-0303'),
  place('k4', '맘스터치 양재역점', '음식점 > 패스트푸드 > 햄버거', '서울 서초구 양재동', 127.0341, 37.4847, '02-579-1177'),
  place('k5', '더진국 설렁탕 강남', '음식점 > 한식 > 설렁탕', '서울 강남구 논현동', 127.0288, 37.5105, '02-511-2222'),
  place('k6', '피자스쿨 서초점', '음식점 > 양식 > 피자', '서울 서초구 방배동', 126.9971, 37.4818, '02-599-0808'),
  place('k7', '봉피양 양재', '음식점 > 한식 > 육류,고기', '서울 서초구 양재동', 127.0388, 37.4701, '02-529-5300'),
  place('k8', '스타벅스 강남대로점', '음식점 > 카페 > 커피전문점', '서울 강남구 역삼동', 127.0284, 37.4995, '1522-3232'),
  place('k9', '이차돌 교대점', '음식점 > 한식 > 육류,고기', '서울 서초구 서초동', 127.0155, 37.4931, '02-3482-9900'),
  place('k10', '한신포차 강남역', '음식점 > 한식 > 해물,생선', '서울 강남구 역삼동', 127.0271, 37.4972, '02-556-1234'),
  place('k11', '유가네닭갈비 강남', '음식점 > 한식 > 닭요리', '서울 강남구 역삼동', 127.029, 37.4982, '02-501-6600'),
  place('k12', '연남토마 서초', '음식점 > 일식 > 돈까스', '서울 서초구 서초동', 127.019, 37.4915, '02-585-7700'),
  place('k13', '더벤티 매봉역점', '음식점 > 카페 > 커피전문점', '서울 강남구 도곡동', 127.0335, 37.4869, ''),
  place('k14', '갓덴스시 강남', '음식점 > 일식 > 초밥,롤', '서울 강남구 역삼동', 127.0281, 37.4979, '02-561-3355'),
  place('k15', '북창동순두부 서초', '음식점 > 한식 > 찌개,전골', '서울 서초구 서초동', 127.017, 37.4939, '02-582-9900'),
  place('k16', '미분당 강남', '음식점 > 아시아음식 > 베트남음식', '서울 강남구 역삼동', 127.0269, 37.4968, ''),
  place('k17', '오늘도청춘 방배', '음식점 > 한식 > 육류,고기', '서울 서초구 방배동', 126.9968, 37.4802, '02-599-3300'),
  place('k18', '샐러디 강남역점', '음식점 > 양식 > 샐러드', '서울 강남구 역삼동', 127.0278, 37.4989, ''),
  // 서비스 지역 밖 (관악구) — 필터로 걸러져야 함
  place('k19', '서울대입구 백반집', '음식점 > 한식 > 백반,가정식', '서울 관악구 봉천동', 126.9412, 37.4813, ''),
  place('k20', '태국식당 방콕 송파', '음식점 > 아시아음식 > 태국음식', '서울 송파구 잠실동', 127.0855, 37.5112, '02-421-7788'),
];

function place(
  id: string,
  name: string,
  category: string,
  address: string,
  lng: number,
  lat: number,
  phone: string,
): KakaoPlace {
  return {
    id,
    place_name: name,
    category_name: category,
    address_name: address,
    road_address_name: address,
    x: String(lng),
    y: String(lat),
    phone,
    place_url: `https://place.map.kakao.com/${id}`,
  };
}
